version: '3.8'

services:
  github-repo-analyzer:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/app
    working_dir: /app
    command: ["--help"]
    
  # Development service with live reload
  github-repo-analyzer-dev:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/app
    working_dir: /app
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
