site_name: GitHub Repository Analyzer
site_description: A CLI tool to analyze GitHub repositories for users and organizations
site_author: Ryan Kane
site_url: https://github.com/rmkane/github-repo-analyzer

# Repository
repo_name: rmkane/github-repo-analyzer
repo_url: https://github.com/rmkane/github-repo-analyzer
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: true
            show_category_heading: true
            show_if_no_docstring: true
            members_order: source
            filters: ["!^_"]
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - minify:
      minify_html: true

# Page tree
nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - User Guide:
    - Configuration: user-guide/configuration.md
  - API Reference:
    - Core: api/core.md
    - Configuration: api/config.md
    - Validation: api/validation.md
    - Logging: api/loggers.md
    - Formatters: api/formatters.md
    - Utils: api/utils.md

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rmkane
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/github-repo-analyzer/
  version:
    provider: mike
